name: Đóng vấn đề
on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "cũ"
          stale-issue-message: "Cái này cũ do không có hoạt động trong 30 ngày."
          close-issue-message: "Cái này đóng do không có hoạt động trong 14 ngày từ khi được đánh dấu \"cũ\"."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
